GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NDZiMzY2NjdiNTcxNjhmM2VhODE5ZjYiLCJpYXQiOjE2ODQ3NDg2MTV9.vUjHQZMQAO8vli6dLUGdNmrDj0NGTslc6SfpFv2gG8o

{
  "title": "bldadg1",
  "author": "authdor1",
  "url": "randourl.com",
  "likes": 2
}